# Generated by Django 5.2.6 on 2025-09-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_studentt_contact_alter_studentt_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentt',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='studentt',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
